### ISSUE TITLE
Urls.py contains wrong value for urlpatterns

### ISSUE THREAD

**Issue by feado** [DrMartiner/django-yandex-kassa#1]
Looks like should be     url(r'^fail/?$', views.FailPageView.as_view(), name='kassa_fail') instead of     url(r'^fal/?$', views.FailPageView.as_view(), name='kassa_fail')

**Comment by DrMartiner** [comment]
What is the difference? We are have not many url's patterns for confuse it, but I'll make this changes

**Comment by mpyrev** [comment]
Issue is fixed now.
