### ISSUE TITLE
Please update PyPI package

### ISSUE THREAD

**Issue by codefo** [DrMartiner/django-yandex-kassa#12]
The last update was in January 2016 😞

**Comment by DrMartiner** [comment]
@codefo I uploaded to PyPi. The latest version is 0.9.13. I'm going to develop this package in the near furure

**Comment by DrMartiner** [comment]
@codefo I updated the lib to [0.9.14](https://pypi.python.org/pypi/django-yandex-kassa/0.9.14)

**Comment by codefo** [comment]
Thanks!
