### ISSUE TITLE
Обнаруженные ошибки

### ISSUE THREAD

**Issue by chewarer** [DrMartiner/django-yandex-kassa#15]
Здравствуйте.
Спасибо за модуль.
После установки наткнулся на пару ошибок:

1. Не показывался список способов оплаты
В settinsg.py в строке:
YANDEX_KASSA_PAYMENT_TYPE = ['ab', 'ac', 'gp', 'pb', 'pc', 'wm']
элементы списка нужно перевести в верхний регистр, или лучше сделать регистронезависимую проверку.
2. При выполнении makemigrations, у меня создается миграция 0006_auto_..... в модуле yandex_kassa.

**Comment by DrMartiner** [comment]
@chewarer Thanks a lot for your report! I fixed and made new version [0.9.14](https://pypi.python.org/pypi/django-yandex-kassa/0.9.14)
